title: "Backrooms 日本語翻訳"
description: "The Backroomsの日本語翻訳サイト"
remote_theme: pages-themes/cayman@v0.2.0  


plugins:
  - jekyll-remote-theme

baseurl: "/backrooms-translation"  
url: "https://mackerelmimi.github.io"  


style: assets/css/custom.css

include:
  - assets/css/custom.css
